In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("India_Cities.csv")

In [3]:
df.head()

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Delhi,28.6600,77.2300,India,IN,Delhi,admin,29617000.0,16753235.0
1,Mumbai,18.9667,72.8333,India,IN,Mahārāshtra,admin,23355000.0,12478447.0
2,Kolkāta,22.5411,88.3378,India,IN,West Bengal,admin,17560000.0,4496694.0
3,Bangalore,12.9699,77.5980,India,IN,Karnātaka,admin,13707000.0,8443675.0
4,Chennai,13.0825,80.2750,India,IN,Tamil Nādu,admin,11324000.0,6727000.0

In [4]:
df = df[['city', 'lat', 'lng', 'population']]
df.columns = [
    'city',
    'latitude',
    'longitude',
    'population'
]

In [5]:
df['city'] = (
    df['city']
    .str.encode('latin1', errors='ignore')  # Added errors='ignore' here
    .str.decode('utf-8', errors='ignore')
)

In [6]:
df.head(10)

        city  latitude  longitude  population
0      Delhi   28.6600    77.2300  29617000.0
1     Mumbai   18.9667    72.8333  23355000.0
2     Kolkta   22.5411    88.3378  17560000.0
3  Bangalore   12.9699    77.5980  13707000.0
4    Chennai   13.0825    80.2750  11324000.0
5    Hyderbd   17.3667    78.4667   9746000.0
6       Pune   18.5196    73.8553   7764000.0
7    Ahmadbd   23.0300    72.5800   7410000.0
8       Srat   21.1700    72.8300   5807000.0
9    Lucknow   26.8470    80.9470   3382000.0

In [7]:
df = df.drop_duplicates(
    subset='city'
)

In [8]:
df = df[
    df['population'] > 500000
]

In [9]:
df = df.sort_values(
    by='population',
    ascending=False
)

In [10]:
df = df.reset_index(drop=True)

In [11]:
print(len(df.city))

92

In [12]:
def assign_region(lat):

    if lat > 26:
        return "North"

    elif lat < 15:
        return "South"

    elif lat > 20:
        return "Central"

    else:
        return "West/East"

In [13]:

def assign_store_type(pop):

    if pop > 10000000:
        return "Hypermarket"

    elif pop > 1500000:
        return "Regional Hub"

    else:
        return "Retail Store"

In [14]:
df['store_type'] = (
    df['population']
    .apply(assign_store_type)
)

In [15]:
np.random.seed(42)

df['monthly_demand'] = (
    (
        df['population'] / 500
    )
    *
    np.random.uniform(
        0.8,
        1.2,
        size=len(df)
    )
).astype(int)

In [16]:
df['demand_variability'] = np.random.choice(
    ['Low','Medium','High'],
    size=len(df),
    p=[0.3,0.5,0.2]
)

In [17]:
def assign_priority(store):

    if store == "Hypermarket":
        return "High"

    elif store == "Regional Hub":
        return "Medium"

    else:
        return "Low"

In [18]:
def assign_sla(priority):

    if priority == "High":
        return 24

    elif priority == "Medium":
        return 48

    else:
        return 72

In [19]:


def assign_region(lat):

    if lat > 26:
        return "North"

    elif lat < 15:
        return "South"

    elif lat > 20:
        return "Central"

    else:
        return "West/East"

df['region'] = (
    df['latitude']
    .apply(assign_region)
)

In [20]:
df['priority_level'] = (
    df['store_type']
    .apply(assign_priority)
)

In [21]:
df['delivery_sla_hours'] = (
    df['priority_level']
    .apply(assign_sla)
)

In [22]:
df['transport_cost_factor'] = np.random.uniform(
    2,
    6,
    size=len(df)
)

In [23]:
df['store_id'] = [
    f"S{i+1}"
    for i in range(len(df))
]

In [24]:
df = df[
    [
        'store_id',
        'city',
        'latitude',
        'longitude',
        'population',
        'store_type',
        'monthly_demand',
        'demand_variability',
        'priority_level',
        'region',
        'delivery_sla_hours',
        'transport_cost_factor'
    ]
]

In [25]:

print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nStore Type Distribution:")
print(df['store_type'].value_counts())
df.to_csv(
    "cleaned_supply_chain_data.csv",
    index=False
)

  store_id       city  latitude  longitude  population   store_type  \
0       S1      Delhi   28.6600    77.2300  29617000.0  Hypermarket
1       S2     Mumbai   18.9667    72.8333  23355000.0  Hypermarket
2       S3     Kolkta   22.5411    88.3378  17560000.0  Hypermarket
3       S4  Bangalore   12.9699    77.5980  13707000.0  Hypermarket
4       S5    Chennai   13.0825    80.2750  11324000.0  Hypermarket

   monthly_demand demand_variability priority_level     region  \
0           56261             Medium           High      North
1           55131             Medium           High  West/East
2           38379             Medium           High    Central
3           28495             Medium           High      South
4           19531             Medium           High      South

   delivery_sla_hours  transport_cost_factor
0                  24               3.031767
1                  24               4.639936
2                  24               5.268889
3                  24               4.220803
4                  24               4.118602

Dataset Shape:
(92, 12)

Store Type Distribution:
store_type
Retail Store    66
Regional Hub    21
Hypermarket      5
Name: count, dtype: int64